apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecosia-treeminer-tor
  labels:
    app: ecosia-treeminer-tor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecosia-treeminer-tor
  template:
    metadata:
      labels:
        # This will be used in the service to send requests to the pod
        app: ecosia-treeminer-tor
    spec:
      containers:
      # Miner container
      - name: miner
        image: majorcadevs/ecosia-treeminer
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        # Store logs in a pod-level volume
        volumeMounts:
        - name: miner-logs
          mountPath: /ecosia-treeminer/logs/
        # "healthcheck"
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 30
        # The readiness probe here is only to show what it looks like, but it is not useful for
        # that simple deployment
        # readinessProbe:
        #  httpGet:
        #    path: /
        #    port: http
        #  initialDelaySeconds: 5
        #  periodSeconds: 1
        env:
          - name: PROXY
            value: socks5://localhost:9050
      # Tor container
      - name: tor
        image: amgxv/tor:stable
        ports:
        - containerPort: 9050
          name: socks-proxy
          protocol: TCP
        volumeMounts:
          - mountPath: /etc/tor/
            name: tor-config
        livenessProbe:
          tcpSocket:
            port: socks-proxy
          initialDelaySeconds: 10
          periodSeconds: 30
      volumes:
      - name: miner-logs
        emptyDir: {}
      - name: tor-config
        configMap:
          name: ecosia-treeminer-tor-config
          items:
          - key: tor-config
            path: torrc
