# Define persistent storage for Prometheus (PVC)
prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          storageClassName: local-storage # If using local cluster, do not use: do-block-storage
          volumeMode: Filesystem # only for local cluster
          resources:
            requests:
              storage: 5Gi

# Define persistent storage for Grafana (PVC)
grafana:
  # Set password for Grafana admin user
  adminPassword: '72JL6KpXW<zH76dErMQmP354~^T2CE75' # random password, you may want to change it
  persistence:
    enabled: true
    storageClassName: local-storage # do-block-storage
    volumeMode: Filesystem # only for local cluster
    accessModes: ["ReadWriteOnce"]
    size: 5Gi

# Define persistent storage for Alertmanager (PVC)
alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          storageClassName: local-storage # do-block-storage
          volumeMode: Filesystem # only for local cluster
          resources:
            requests:
              storage: 5Gi

# Change default node-exporter port
prometheus-node-exporter:
  service:
    port: 9100 # this is only a workaround for DO: 30206
    targetPort: 9100 # 30206

# Disable Etcd metrics
kubeEtcd:
  enabled: false

# Disable Controller metrics
kubeControllerManager:
  enabled: false

# Disable Scheduler metrics
kubeScheduler:
  enabled: false